# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:13-alpine
    #restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
#    logging:
#      options:
#        max-size: 10m
#        max-file: "3"
    volumes: 
      - ./sql:/sql
#     - ./data:/var/lib/postgresql/data
#      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
#      # copy the sql script to fill tables
#      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql


